### PR TITLE
Fix tests by wrapping everything in a transaction

### PR DESCRIPTION
**Pull request by GustavoCaso**
#6 
@solnic still a WIP, but I wanted to share the progress so far.

I'm missing the specific test about `postgres` and the `jruby` part, also I want to clean it up a bit, but wrapping every test in a transaction avoid having inconsistency in the test, at least locally.

I will keep working but please feel free to comment as much as need it

### CODE REVIEW

**Comment by GustavoCaso** [comment]
After this commit 9740d44 all the test are passing and correctly 😄

**Comment by solnic** [comment]
You know what, I just realized (sorry!) that there's no reason why we should be testing against multiple sql dbs. So let's just use postgres and call it a day.

**Comment by GustavoCaso** [comment]
No problem :)

**Comment by GustavoCaso** [comment]
Fixed with #6

**Pull request closed without merging**
